### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by SeqSEE** [FoxelTeam/Foxel#11]
I'm probably doing something wrong....
[crash.txt](https://github.com/FoxelTeam/Foxel/files/3828182/crash.txt)

**Comment by NTT1906** [comment]
I can fix it

**Comment by SeqSEE** [comment]
Did I mess up somewhere in the setup? @NTT1906

**Comment by NTT1906** [comment]
No, that we fault

**Comment by SeqSEE** [comment]
Oh okay, well happy to test again after any changes :)

**Comment by NTT1906** [comment]
Ok 😅

**Comment by GamakCZ** [comment]
Use phar from releases, source is buggy
