### ISSUE TITLE
i need a .phar of the latest commit to test it please

### ISSUE THREAD

**Issue by mote166** [FoxelTeam/Foxel#17]
i tried putting the src in the root directory but it didn't work

**Comment by GamakCZ** [comment]
https://github.com/FoxelTeam/Foxel/releases/tag/1.12%261.13

**Comment by mote166** [comment]
@GamakCZ that is not the latest commit i want the multiprotocol one because the other one has an issue which kicks players out upon joining the server for skin issue

**Comment by NTT1906** [comment]
Here

**Comment by GamakCZ** [comment]
https://github.com/FoxelTeam/Foxel/runs/318262709

**Comment by GamakCZ** [comment]
You can download artifacts from github ci
