### ISSUE TITLE
Loading screen problem

### ISSUE THREAD

**Issue by NTT1906** [FoxelTeam/Foxel#19]
![Screenshot_2019-11-25-12-53-30-306_com mojang minecraftpe](https://user-images.githubusercontent.com/54394881/69538955-0aed2680-0fb6-11ea-835f-d5953554a027.png)
Stuck at loading screen in Android player in Mcpe 1.14.0.51, no crash or any bug :'(

**Comment by CuongZ** [comment]
I think 1.14 is not fully supported by this software so the bug/error is possible.
I joined my server ( using lastest Foxel src / use DevTool's makeserver to get .phar file) but it worked in 1.13.1 but in 1.14.0.51 its says Incompatible API or Server Outdated :(

**Comment by NTT1906** [comment]
No, i use latest Foxel commit, i think u are using latest Release foxel

**Comment by GamakCZ** [comment]
We are supporting only 1.14 with protocol 389. Maybe you have different protocol version

**Comment by NTT1906** [comment]
![Screenshot_2019-11-26-00-45-37-099_com mojang minecraftpe](https://user-images.githubusercontent.com/54394881/69564726-207a4480-0fe6-11ea-9d92-78d561a0f457.png)

**Comment by NTT1906** [comment]
That 389

**Comment by CuongZ** [comment]
![image](https://user-images.githubusercontent.com/34135258/69621893-801e3180-1072-11ea-825e-d894b7090253.png) it worked on protocol 389
![image](https://user-images.githubusercontent.com/34135258/69621935-97f5b580-1072-11ea-9dd0-ec7887f1419d.png)

**Comment by CuongZ** [comment]
seem an plugin called [CustomAlerts](https://github.com/EvolSoft/CustomAlerts) made the message that say Server outdated:
+ While join server with CustomAlerts installed
![image](https://user-images.githubusercontent.com/34135258/69624351-1f452800-1077-11ea-8b71-ef74d3acc2cc.png)

+ While join server without CustomAlerts
![image](https://user-images.githubusercontent.com/34135258/69624222-dc835000-1076-11ea-8764-783d90de64f5.png)
(translated with tl;dr: Server outdated)

**Comment by NTT1906** [comment]
Android Player is a big problem, some multiprotocol code may only support for Window 10 Edition :/

**Comment by GamakCZ** [comment]
For me it's working on android too.
